#!/usr/bin/env node
// Generates src/generated/** from ../openapi.yaml. Run it through ./scripts/sync-sdk-core.sh.
// Usage: node scripts/generate.mjs [--out <dir>]   (default: src/generated)
//
// Output, every file headed "GENERATED … Do not edit":
//   types.gen.ts        hey-api's @hey-api/typescript plugin: one type per components.schemas entry,
//                       plus the per-operation request/response types.
//   schemas.gen.ts      a name-listed `export type { … }` barrel of every components.schemas key except
//                       the documented exclusions in scripts/schema-barrel-exclusions.mjs, so the public
//                       type names are exactly the contract's schema names.
//   api-version.gen.ts  COVE_API_VERSION = info.version.
//   error-codes.gen.ts  ERROR_CODES = the ErrorCode enum, in contract order.
//
// Staging: everything is written to a sibling `.gen-tmp-*` directory and renamed over the output at the
// end, so a crash never leaves a half-written output. For the default output the staging directory sits
// in the package root (outside src/, which tsconfig.json compiles); renameSync needs it on the output's
// filesystem, and /tmp is a tmpfs both on dev VMs and in CI, so the OS temp dir is only used for
// hey-api's own scratch output, which is read and never renamed.
import { createClient } from "@hey-api/openapi-ts";
import { chmodSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve, isAbsolute } from "node:path";
import { fileURLToPath } from "node:url";
import { SCHEMA_BARREL_EXCLUSIONS } from "./schema-barrel-exclusions.mjs";

const root = fileURLToPath(new URL("..", import.meta.url));
const spec = join(root, "..", "openapi.yaml");
const outArg = process.argv.indexOf("--out");
if (outArg !== -1 && !process.argv[outArg + 1]) {
  console.error("usage: node scripts/generate.mjs [--out <dir>]");
  process.exit(2);
}
const out = resolve(outArg === -1 ? join(root, "src", "generated") : process.argv[outArg + 1]);
const HEADER =
  "// GENERATED by sdk/typescript/scripts/generate.mjs from sdk/openapi.yaml. Do not edit.\n" +
  "// Regenerate with ./scripts/sync-sdk-core.sh.\n\n";

/** info.version of the contract (the server's API_VERSION). */
function infoVersion(yaml) {
  const m = yaml.match(/\ninfo:\n(?:(?: {2,}.*)?\n)*? {2}version: '?([^'\n]+)'?\n/);
  if (!m) throw new Error("generate: info.version not found in sdk/openapi.yaml");
  return m[1];
}

/** The ErrorCode enum as a const list, in contract order. The ErrorCode type itself lives in types.gen.ts. */
function errorCodes(yaml) {
  const m = yaml.match(/\n {4}ErrorCode:\n(?:.*\n)*? {6}enum:\n((?: {6}- .+\n)+)/);
  if (!m) throw new Error("generate: ErrorCode schema with an enum list not found in sdk/openapi.yaml");
  const codes = m[1]
    .split("\n")
    .filter(Boolean)
    .map((l) => l.replace(/^ {6}- /, "").replace(/^'(.*)'$/, "$1"));
  return (
    'import type { ErrorCode } from "./types.gen.js";\n\n' +
    "export const ERROR_CODES = [\n" +
    codes.map((c) => `  ${JSON.stringify(c)},\n`).join("") +
    "] as const satisfies readonly ErrorCode[];\n"
  );
}

/**
 * Every key under components.schemas, sorted, as one name-listed type re-export, minus
 * SCHEMA_BARREL_EXCLUSIONS (each named in a comment in the output; src/ergonomic.ts exports the
 * corrected type). A stale exclusion, one that is no longer a schema, is an error.
 */
function schemaBarrel(yaml) {
  const lines = yaml.split("\n");
  const start = lines.indexOf("  schemas:");
  if (start === -1) throw new Error("generate: components.schemas not found in sdk/openapi.yaml");
  const names = [];
  for (const line of lines.slice(start + 1)) {
    if (/^ {0,2}[A-Za-z]/.test(line)) break; // the next components.* key, or the next top-level key
    const m = line.match(/^ {4}([A-Za-z0-9_]+):$/);
    if (m) names.push(m[1]);
  }
  if (names.length === 0) throw new Error("generate: components.schemas is empty");
  const excluded = Object.keys(SCHEMA_BARREL_EXCLUSIONS).sort();
  const stale = excluded.filter((n) => !names.includes(n));
  if (stale.length) throw new Error(`generate: schema-barrel-exclusions.mjs names non-schemas: ${stale.join(", ")}`);
  const listed = names.filter((n) => !excluded.includes(n)).sort();
  return (
    "// Left out (scripts/schema-barrel-exclusions.mjs; src/ergonomic.ts exports the corrected type):\n" +
    excluded.map((n) => `//   ${n}: ${SCHEMA_BARREL_EXCLUSIONS[n]}\n`).join("") +
    "\nexport type {\n" + listed.map((n) => `  ${n},\n`).join("") + '} from "./types.gen.js";\n'
  );
}

// Staging parent: the package root for outputs inside it (never src/, see above), else the output's parent.
const rel = relative(root, out);
const inside = rel !== "" && !rel.startsWith("..") && !isAbsolute(rel);
const stageParent = inside ? root : dirname(out);
for (const entry of readdirSync(root)) {
  if (entry.startsWith(".gen-tmp-")) rmSync(join(root, entry), { recursive: true, force: true });
}
mkdirSync(stageParent, { recursive: true });

const yaml = readFileSync(spec, "utf8");
const work = mkdtempSync(join(tmpdir(), "cove-sdk-gen-"));
const stage = mkdtempSync(join(stageParent, ".gen-tmp-"));
chmodSync(stage, 0o755); // mkdtemp creates 0700; the output directory should read like any other
let aside = null;
try {
  await createClient({
    input: spec,
    output: {
      path: join(work, "hey"),
      // Pinned so the output never depends on the caller's cwd or a tsconfig found by walking up.
      tsConfigPath: join(root, "tsconfig.json"),
      postProcess: [],
    },
    // Types only: no SDK functions, no client, no runtime code.
    // @hey-api/transformers is deliberately NOT listed: with it enabled, its `bigInt` option (default
    // true) turns every int64 into `bigint`; without it the typescript plugin emits `number` for int64
    // (a deliberate choice). tests/types/int64.check.ts pins that.
    plugins: ["@hey-api/typescript"],
    logs: { level: "silent", file: false },
  });
  writeFileSync(join(stage, "types.gen.ts"), HEADER + readFileSync(join(work, "hey", "types.gen.ts"), "utf8"));
  writeFileSync(join(stage, "schemas.gen.ts"), HEADER + schemaBarrel(yaml));
  writeFileSync(
    join(stage, "api-version.gen.ts"),
    HEADER + `export const COVE_API_VERSION = ${JSON.stringify(infoVersion(yaml))};\n`,
  );
  writeFileSync(join(stage, "error-codes.gen.ts"), HEADER + errorCodes(yaml));
  // Swap without a window where `out` is gone: move the old output aside (same filesystem, outside
  // src/), rename the stage onto `out`, then drop the aside copy. If the second rename fails, the
  // old output is put back before the error propagates.
  aside = mkdtempSync(join(stageParent, ".gen-tmp-old-"));
  const old = join(aside, "generated");
  let moved = false;
  try {
    renameSync(out, old);
    moved = true;
  } catch (e) {
    if (e.code !== "ENOENT") throw e; // no previous output: nothing to set aside
  }
  try {
    renameSync(stage, out);
  } catch (e) {
    if (moved) renameSync(old, out);
    throw e;
  }
} finally {
  rmSync(work, { recursive: true, force: true });
  rmSync(stage, { recursive: true, force: true });
  if (aside) rmSync(aside, { recursive: true, force: true });
}
